if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

. "$HOME/.bashrc"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

##
# Your previous /Users/vmuppalla/.bash_profile file was backed up as /Users/vmuppalla/.bash_profile.macports-saved_2012-12-19_at_17:46:49
##

# MacPorts Installer addition on 2012-12-19_at_17:46:49: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/vmuppalla/.bash_profile file was backed up as /Users/vmuppalla/.bash_profile.macports-saved_2013-01-02_at_13:21:18
##

# MacPorts Installer addition on 2013-01-02_at_13:21:18: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

-e 
export NVM_DIR="/Users/vmuppalla/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
